# Generated by Django 3.0.6 on 2022-03-27 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anime_PlanetID', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=2000)),
                ('Alternative_Name', models.CharField(max_length=2000)),
                ('Rating_score', models.FloatField(default=0)),
                ('Number_votes', models.IntegerField(default=0)),
                ('Tags', models.CharField(max_length=2000)),
                ('Content_Warning', models.CharField(max_length=2000)),
                ('Type', models.CharField(max_length=2000)),
                ('Episodes', models.IntegerField(default=0)),
                ('Finished', models.CharField(max_length=10)),
                ('Duration', models.IntegerField(default=0)),
                ('StartYear', models.IntegerField(default=0)),
                ('EndYear', models.IntegerField(default=0)),
                ('Season', models.CharField(max_length=2000)),
                ('Studios', models.CharField(max_length=2000)),
                ('Synopsis', models.CharField(max_length=2000)),
                ('Url', models.CharField(max_length=5000)),
                ('picture_url', models.CharField(max_length=5000)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Myrating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_recommend.Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_recommend.Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
